### PR TITLE
Add the DNS nameserver serving on 172.28.128.4 network. Fix #89

### LINKED ISSUE #89: External DNS resolution doesn't work with Openshift Origin 1.3.1
Since the upgrade to Openshift Origin 1.3.1, the DNS Servers defined within a docker container are

```
nameserver 172.30.0.1,
nameserver 10.0.2.3
```

and not 

```
nameserver 172.28.128.4,
nameserver 10.0.2.3
```

This behaviour could be explained how the dnsIP is defined within the node yaml config file created 

With 1.1.6

```
 more /var/lib/openshift/openshift.local.config/node-172.28.128.4/node-config.yaml
allowDisabledDocker: false
apiVersion: v1
authConfig:
  authenticationCacheSize: 1000
  authenticationCacheTTL: 5m
  authorizationCacheSize: 1000
  authorizationCacheTTL: 5m
dnsDomain: cluster.local
dnsIP: 172.28.128.4
```

and 1.3.1

```
cat /var/lib/openshift/openshift.local.config/node-172.28.128.4/node-config.yaml
allowDisabledDocker: false
apiVersion: v1
authConfig:
  authenticationCacheSize: 1000
  authenticationCacheTTL: 5m
  authorizationCacheSize: 1000
  authorizationCacheTTL: 5m
dnsDomain: cluster.local
dnsIP: ""
```

### PR DESCRIPTION
**Pull request by cmoulliard**
- Add the DNS nameserver serving on 172.28.128.4 network. Fix #89

### CODE REVIEW

**Comment by cmoulliard** [comment]
Tested successfully 

```
[vagrant@vagrant ~]$ cat /var/lib/openshift/openshift.local.config/node-172.28.128.4/node-config.yaml
allowDisabledDocker: false
apiVersion: v1
authConfig:
  authenticationCacheSize: 1000
  authenticationCacheTTL: 5m
  authorizationCacheSize: 1000
  authorizationCacheTTL: 5m
dnsDomain: cluster.local
dnsIP: "172.28.128.4"
dockerConfig:
  execHandlerName: native
imageConfig:
  format: openshift/origin-${component}:${version}
  latest: false
iptablesSyncPeriod: 5s
kind: NodeConfig
masterKubeConfig: node.kubeconfig
networkConfig:
  mtu: 1450
  networkPluginName: ""
nodeIP: ""
nodeName: 172.28.128.4
podManifestConfig:
  path: /var/lib/openshift/openshift.local.manifests
  fileCheckIntervalSeconds: 10
servingInfo:
  bindAddress: 0.0.0.0:10250
  bindNetwork: tcp4
  certFile: server.crt
  clientCA: node-client-ca.crt
  keyFile: server.key
  namedCertificates: null
volumeConfig:
  localQuota:
    perFSGroup: null
volumeDirectory: /var/lib/openshift/openshift.local.volumes
kubeletArguments:
  "read-only-port":
    - "10255"

[vagrant@vagrant ~]$ oc rsh router-1-9lp04
sh-4.2$ wget www.github.com
--2016-06-14 13:56:52--  http://www.github.com/
Resolving www.github.com (www.github.com)... 192.30.252.128
Connecting to www.github.com (www.github.com)|192.30.252.128|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://www.github.com/ [following]
--2016-06-14 13:56:53--  https://www.github.com/
Connecting to www.github.com (www.github.com)|192.30.252.128|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://github.com/ [following]
--2016-06-14 13:56:53--  https://github.com/
Resolving github.com (github.com)... 192.30.252.128
Connecting to github.com (github.com)|192.30.252.128|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
index.html: Permission denied
```

**Comment by jimmidyson** [comment]
According to https://github.com/fabric8io/fabric8-installer/issues/89#issuecomment-225887575 this shouldn't be required though right? So why do we need to do this?

**Comment by cmoulliard** [comment]
If we don't include the dnsIP, openshift origin 1.3.1 will add this address that we don't route with our Vagrant VM Box

```
nameserver: 172.30.0.1
```

**Comment by jimmidyson** [comment]
That is the internal cluster IP of the kubernetes master that was mentioned in https://github.com/fabric8io/fabric8-installer/issues/89#issuecomment-225887575. Is that not accessible from a pod in your set up? You should be able to see that IP in `oc get services` as the internal API server cluster address.

**Comment by cmoulliard** [comment]
If the docker container must fetch an external resource, then this DNS Server is required `nameserver: 172.28.128.4` but as this address has been removed from the node config of openshift origin 1.3.1, curl/wget won't work when launched by the docker entrypoint (= shell script)

**Comment by jimmidyson** [comment]
So with this set up can you resolve internal service names, etc?

**Comment by cmoulliard** [comment]
There is still a second DNS server defined `nameserver 10.0.2.15` within the /etc/resolv.conf file

**Comment by jimmidyson** [comment]
That's great, but doesn't answer my question :) In a pod, can you resolve cluster services via DNS with this configuration?

**Comment by cmoulliard** [comment]
This PR is not required. We should, for openshift 1.3.1, keep for the node-config.yaml file the field dnsIP: "" as it is but add to the /etc/resolv.conf file of our Vagrant VM Box 8.8.8.8 & 8.8.4.4 as nameservers and  then the docker container can fetch external resources

**Comment by cmoulliard** [comment]
No

On Tue, Jun 14, 2016 at 5:33 PM, Jimmi Dyson notifications@github.com
wrote:

> That's great, but doesn't answer my question :) In a pod, can you resolve
> cluster services via DNS with this configuration?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/fabric8io/fabric8-installer/pull/90#issuecomment-225920653,
> or mute the thread
> https://github.com/notifications/unsubscribe/AAcTrsA58ZR-WelLaPLHsdXMhnPmzqzbks5qLsnBgaJpZM4I1Whi
> .

## 

Charles Moulliard
Apache Committer & PMC / Architect @RedHat
Twitter : @cmoulliard | Blog :  http://cmoulliard.github.io

**Pull request closed without merging**
